config/routes.rb
HackersAndHounds::Application.routes.draw do
  get "welcome/index"
  get "static_pages/about"
  get "static_pages/contact"
  get "pages/about"
  get "pages/contact"

  resources :articles

  root 'welcome#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name, presence: true
	validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @listing }
      else
        format.html { render action: 'new' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackersAndHounds</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="pure-menu pure-menu-open pure-menu-horizontal pure-u">
    <ul>
    	<li><a href="/welcome/index">Home</a></li>
      <li><a href="/static_pages/about">About</a></li>
      <li><a href="/static_pages/contact">Contact</a></li>
    </ul>
	</div>

<%= yield %>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1>Listing listings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.name %></td>
        <td><%= listing.description %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/static_pages/about.html.erb
<div class="content">
	<h1 class="header-title handwriting">Hello Hackers!</h1>

	<div class="body-text" style="margin-bottom:100px;">
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu sit amet massa fringilla egestas et a leo. Donec vitae auctor enim, quis posuere nulla. Aliquam erat volutpat. Mauris eget ligula ante. Curabitur rutrum risus et tempor auctor. Vivamus a blandit lacus. Praesent ut fringilla arcu. Cras lorem nulla, auctor a tincidunt non, ultricies ut sapien. Nam vel purus ut sem sagittis sagittis quis nec erat. Vestibulum mattis interdum aliquet. Sed tempus, erat in molestie cursus, dui tortor pulvinar elit, id volutpat tellus lorem vitae augue. Fusce tincidunt tristique quam et vehicula. Sed non dui varius, lobortis eros eu, ornare nisi. Vestibulum lobortis egestas turpis id bibendum. Phasellus sollicitudin, nisl a tempus consectetur, ipsum massa vulputate sem, id imperdiet dolor ante et arcu. Nunc ornare nunc sapien, id sagittis est gravida in.</p>

		<p>Morbi in nisl sit amet est vehicula laoreet varius non quam. Maecenas ut justo diam. Fusce lacus tortor, convallis in aliquet quis, pellentesque eget dui. Nullam at ullamcorper turpis, vel adipiscing tellus. Maecenas placerat posuere massa, sit amet tempus risus imperdiet sit amet. Sed congue elit eu orci sollicitudin ultricies. In in tortor condimentum, dictum dolor sed, vestibulum nulla.</p>

		<p>Morbi vestibulum vehicula turpis. Nulla in viverra dui, id varius mauris. Proin quis mattis justo. Pellentesque eu tellus imperdiet, hendrerit ipsum quis, viverra metus. Ut at lorem ante. Fusce adipiscing mauris et neque pharetra, id elementum urna vehicula. Cras rhoncus tortor eget lorem eleifend mattis. In porttitor velit sit amet aliquet suscipit. Integer rhoncus odio et magna dictum, eget ultrices nisl mollis.</p>

		<p>Aliquam erat volutpat. Nulla diam odio, ultricies a laoreet quis, sagittis eu leo. Nunc leo diam, ultrices pulvinar sagittis sit amet, posuere id augue. Sed vestibulum sed augue in aliquet. Pellentesque pellentesque porttitor tortor id lacinia. Sed id placerat turpis. Proin rutrum, magna nec vehicula vestibulum, leo est auctor orci, pharetra imperdiet nisi velit quis sapien. Maecenas consectetur congue nisi, in hendrerit leo vulputate vitae. Integer ullamcorper velit et felis blandit, eget tincidunt orci molestie. Nulla aliquam ac magna et mattis.</p>

		<p>Nam tortor leo, cursus ut tempor ut, eleifend sit amet erat. Quisque egestas non ante ut scelerisque. Aliquam sed suscipit felis, ac gravida magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut quis elementum turpis. Nullam sit amet viverra velit. Pellentesque convallis urna eu velit rutrum, eu laoreet eros tincidunt. Ut vitae dignissim elit. Morbi mollis tellus sit amet enim fringilla sodales. Vivamus bibendum, sapien sed commodo ultricies, ligula elit dictum lorem, vitae tristique neque nulla ut risus. Proin condimentum leo mollis semper rhoncus. Phasellus id elementum mi.</p>
	</div>
</div>

app/views/static_pages/contact.html.erb
<h1 class="header-title handwriting">Contact Me</h1>

app/views/welcome/index.html.erb
<h1>Welcome</h1>